version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    environment:
      SA_PASSWORD: "m@hdi.sds13211"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - E:\mynewssms\log:/var/opt/mssql/log
    restart: on-failure

  web:
    build:
      context: .
      dockerfile: MyShop.Web/Dockerfile
    container_name: myapp_web
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=MyShopApp;User Id=sa;Password=m@hdi.sds13211;TrustServerCertificate=true"
    ports:
      - "5000:5000"
    restart: on-failure


volumes:
  sql_data:
